# encoding: utf-8


namespace :bootstrap do
  desc "Create the Categories"
  task :default_categories => :environment do
    Category.create( :isim => 'Araştırma - Geliştirme')
    Category.create( :isim => 'Bilişim')
    Category.create( :isim => 'Çeviri')
    Category.create( :isim => 'Danışmanlık')
    Category.create( :isim => 'Dış Ticaret')
    Category.create( :isim => 'Editörlük - Yazı İşleri')
    Category.create( :isim => 'Eğitim - Öğretim')
    Category.create( :isim => 'Finans - Banka')
    Category.create( :isim => 'Gayrimenkul')
    Category.create( :isim => 'Güvenlik - Koruma')
    Category.create( :isim => 'Hukuk')
    Category.create( :isim => 'İdari')
    Category.create( :isim => 'İlaç - Biyoteknoloji')
    Category.create( :isim => 'İnsan Kaynakları')
    Category.create( :isim => 'Lojistik')
    Category.create( :isim => 'Mimarlık - Tasarım')
    Category.create( :isim => 'Muhasebe')
    Category.create( :isim => 'Mühendislik')
    Category.create( :isim => 'Müşteri Hizmetleri')
    Category.create( :isim => 'Otomotiv')
    Category.create( :isim => 'Perakende - Mağazacılık')
    Category.create( :isim => 'Reklamcılık - Halkla ilişkiler')
    Category.create( :isim => 'Sağlık')
    Category.create( :isim => 'Satış')
    Category.create( :isim => 'Teknik Servis')
    Category.create( :isim => 'Tekstil')
    Category.create( :isim => 'Telekomünikasyon')
    Category.create( :isim => 'Temizlik')
    Category.create( :isim => 'Turizm')
    Category.create( :isim => 'Üretim - Operasyon')
    Category.create( :isim => 'Yapı İşleri')
    Category.create( :isim => 'Yiyecek - İçecek Hizmetleri')
    Category.create( :isim => 'Yönetim - Stratejik Planlama')
    Category.create( :isim => 'Diğer')


    Category.create( :name => 'Accounting Services')
    Category.create( :name => 'Administrative')
    Category.create( :name => 'Advertisement - Public Relations')
    Category.create( :name => 'Architecture - Design')
    Category.create( :name => 'Automotive')
    Category.create( :name => 'Cleaning Services')
    Category.create( :name => 'Construction Services')
    Category.create( :name => 'Counseling')
    Category.create( :name => 'Customer Relations')
    Category.create( :name => 'Editorial')
    Category.create( :name => 'Education')
    Category.create( :name => 'Engineering')
    Category.create( :name => 'Finance - Banking')
    Category.create( :name => 'Food and Beverage Services')
    Category.create( :name => 'Health Services')
    Category.create( :name => 'Human Resources')
    Category.create( :name => 'Information')
    Category.create( :name => 'International Trade')
    Category.create( :name => 'Legal Services')
    Category.create( :name => 'Logistics')
    Category.create( :name => 'Management - Strategic Planning')
    Category.create( :name => 'Pharmaceutical - Biotechnology')
    Category.create( :name => 'Production - Operation Services')
    Category.create( :name => 'Real estate')
    Category.create( :name => 'Research and Development')
    Category.create( :name => 'Retail Services')
    Category.create( :name => 'Sales')
    Category.create( :name => 'Security')
    Category.create( :name => 'Technical Services')
    Category.create( :name => 'Telecommunications')
    Category.create( :name => 'Textile')
    Category.create( :name => 'Translation')
    Category.create( :name => 'Tourism')
    Category.create( :name => 'Other')
  end

  desc "Run all bootstrapping tasks"
  task :all => [:default_categories]
end
